/**
 * AUTO-GENERATED TRPC ROOT ROUTER
 *
 * This file is automatically generated by the Ghost-Dev wizard.
 * It merges all module routers into a single tRPC app router.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * To add a new module, use: asan wizard
 */

import { router, publicProcedure } from "./trpc";

export const appRouter = router({
  // System Health
  health: publicProcedure.query(() => {
    return {
      status: "ASANMOD v1.1.1 OPERATIONAL",
      timestamp: new Date(),
      engine: "Ghost-Dev Modular Architecture",
      modules: ["users", "posts"], // Auto-updated by wizard
    };
  }),

  // Module Routers
  // users: usersRouter,
  // posts: postsRouter,

  // Add new module routers here (auto-generated by wizard)
});

export type AppRouter = typeof appRouter;
